### ISSUE TITLE
Cannot pipe. Not readable.

### ISSUE THREAD

**Issue by vitkarpov** [max-mapper/concat-stream#20]
Here's the point:

```
var concat = require('concat-stream');

process.stdin
    .pipe(concat(function(buff) {
       // do smth
    }))
    .pipe(process.stdout);
```

It gives the following:

```
Error: Cannot pipe. Not readable.
    at ConcatStream.Writable.pipe (.../node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:142:22)
```

Why chaining is broken in this case? Does concat-stream apply this one?

**Comment by raine** [comment]
I think being able to pipe the result of concat stream would make it more "composable". I actually have an use case where I want to either concat a stream into one big array or emit the chunks one at a time to another stream. Callback being the only API makes that a bit difficult.
